CREATE TABLE `auth_user` (
	`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键id',
	`username` VARCHAR(12) NOT NULL COMMENT '用户名(唯一)' COLLATE 'utf8_unicode_ci',
	`password` VARCHAR(32) NOT NULL COMMENT '用户密码' COLLATE 'utf8_unicode_ci',
	`email` VARCHAR(100) NULL DEFAULT NULL COMMENT '用户邮箱' COLLATE 'utf8_unicode_ci',
	`salt` VARCHAR(20) NOT NULL COMMENT '加密盐值' COLLATE 'utf8_unicode_ci',
	`au_flag` TINYINT(4) NOT NULL DEFAULT '1' COMMENT '标志位，0:删除 1存在',
	`gmt_create` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`gmt_modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
	PRIMARY KEY (`id`),
	UNIQUE INDEX `username` (`username`)
)
COMMENT='后台用户表'
COLLATE='utf8_unicode_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;




#部门表
CREATE TABLE `department` (
	`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
	`dept_name` VARCHAR(50) NOT NULL COMMENT '部门名称',
	`is_deleted` INT(11) NOT NULL DEFAULT '0' COMMENT '逻辑删除',
	`gmt_create` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`gmt_modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
	PRIMARY KEY (`id`)
)
COMMENT='部门'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;



#员工表
CREATE TABLE `employee` (
	`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
	`dept_id` INT(11) NOT NULL COMMENT '逻辑外键（部门id）',
	`emp_name` VARCHAR(50) NOT NULL COMMENT '员工名称',
	`gender` CHAR(1) NOT NULL COMMENT '性别',
	`email` VARCHAR(255) NOT NULL COMMENT '邮件',
	`is_deleted` INT(11) NOT NULL DEFAULT '0' COMMENT '逻辑删除(0 ; 1)',
	`gmt_create` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`gmt_modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
	PRIMARY KEY (`id`)
)
COMMENT='员工表'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;


